var fs = require('fs');
var name = [
"import 'package:flutter/services.dart';",
"import 'package:flutter_project/l10n/app_localizations.dart';",
"",
"final RegExp arabicNamePattern = RegExp(",
"  r'^[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FF\\s\\-\\.]+$',",
");",
"",
"final RegExp englishNamePattern = RegExp(r\"^[A-Za-z\\s\\-\\.\\']+$\");",
"",
"final RegExp arabicNameInputPattern = RegExp(",
"  r'[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FF\\s\\-\\.]',",
");",
"",
"final RegExp englishNameInputPattern = RegExp(r\"[A-Za-z\\s\\-\\.\\']\");",
"",
"class NameValidators {",
"  NameValidators._();",
"",
"  static List<TextInputFormatter> arabicInputFormatters() => [",
"    FilteringTextInputFormatter.allow(arabicNameInputPattern),",
"  ];",
"",
"  static List<TextInputFormatter> englishInputFormatters() => [",
"    FilteringTextInputFormatter.allow(englishNameInputPattern),",
"  ];",
"",
"  static String? validateArabicName(String? value, AppLocalizations l10n) {",
"    if (value == null || value.trim().isEmpty) {",
"      return l10n.authErrorNameArabicRequired;",
"    }",
"    if (!arabicNamePattern.hasMatch(value.trim())) {",
"      return l10n.authErrorNameArabicOnly;",
"    }",
"    return null;",
"  }",
"",
"  static String? validateEnglishName(String? value, AppLocalizations l10n) {",
"    if (value == null || value.trim().isEmpty) {",
"      return l10n.authErrorNameEnglishRequired;",
"    }",
"    if (!englishNamePattern.hasMatch(value.trim())) {",
"      return l10n.authErrorNameEnglishOnly;",
"    }",
"    return null;",
"  }",
"}",
""].join('\n');
fs.writeFileSync('lib/shared/validators/name_validators.dart', name);
console.log('name ok');
