var fs = require('fs');
var terms = [
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:flutter_riverpod/flutter_riverpod.dart';",
"import 'package:flutter_project/core/preferences/app_preferences.dart';",
"import 'package:flutter_project/features/auth/data/auth_service.dart';",
"",
"final termsProvider = NotifierProvider<TermsNotifier, bool>(TermsNotifier.new);",
"",
"class TermsNotifier extends Notifier<bool> {",
"  static const prefsKey = 'terms_accepted';",
"",
"  @override",
"  bool build() {",
"    final prefs = ref.watch(sharedPreferencesProvider);",
"    return prefs.getBool(prefsKey) ?? false;",
"  }",
"",
"  Future<void> accept({String? uid}) async {",
"    final prefs = ref.read(sharedPreferencesProvider);",
"    await prefs.setBool(prefsKey, true);",
"    await prefs.setString('terms_accepted_at', DateTime.now().toIso8601String());",
"    if (uid != null) {",
"      await ref.read(firestoreProvider).collection('users').doc(uid).set({",
"        'terms_accepted': true,",
"        'accepted_at': FieldValue.serverTimestamp(),",
"      }, SetOptions(merge: true));",
"    }",
"    state = true;",
"  }",
"",
"  Future<void> syncFromFirestore(String uid) async {",
"    final doc = await ref.read(firestoreProvider).collection('users').doc(uid).get();",
"    if (doc.data()?['terms_accepted'] == true) {",
"      await ref.read(sharedPreferencesProvider).setBool(prefsKey, true);",
"      state = true;",
"    }",
"  }",
"}",
""].join('\n');
fs.writeFileSync('lib/features/auth/presentation/providers/terms_provider.dart', terms);
console.log('done');
