name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      
      - name: Install dependencies
        working-directory: ./functions
        run: npm ci
      
      - name: Deploy Firebase Functions
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > service_account.json
          npx firebase-tools deploy --only functions --project smart-college-app-442cd
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
